[project]
name = "deepresearchagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=0.6.0",
    "ipykernel>=6.29.5",
    "pydantic-ai>=0.0.19",
    "pydantic-ai-slim[openai]>=0.0.19",
    "requests>=2.32.3",
]
